

import streamlit as st
from components import (
    section_header, score_ring, agent_card, render_feedback,
    count_severities, compute_score, severity_badge, topbar,
    severity_bar_chart, score_breakdown,
)

if "result" not in st.session_state or not st.session_state.result:
    st.warning("No review to show yet.")
    if st.button("← Start a review"):
        st.switch_page("pages/2_Pull_Requests.py")
    st.stop()

bug_feedback, style_feedback, final_report = st.session_state.result
diff_shown = st.session_state.get("diff_shown", "")
pr_meta = st.session_state.get("pending_pr_meta") or {}

bug_counts = count_severities(bug_feedback)
style_counts = count_severities(style_feedback)
score = compute_score(bug_counts, style_counts)
score_label = "Good" if score >= 80 else ("Needs Work" if score >= 60 else "At Risk")


h_l, h_r = st.columns([3, 1])
with h_l:
    topbar("CodeCrew / Report", pr_meta.get("repo", "Review Report"), f"PR #{pr_meta.get('pr_number', '—')} · Reviewed just now")
with h_r:
    st.markdown("<div style='height:6px'></div>", unsafe_allow_html=True)
    st.button("Download Report", type="secondary", use_container_width=True)

st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)


s_col, a1_col, a2_col = st.columns([1, 1.4, 1.4], gap="medium")

with s_col:
    score_card = st.container(border=True)
    with score_card:
        score_ring(score, score_label)

with a1_col:
    agent_card(
        "Agent 1 — Bug & Logic",
        "Bugs, logic errors, crash risks",
        [
            f"{bug_counts['critical']} critical",
            f"{bug_counts['warning']} warnings",
            f"{bug_counts['info']} notes",
        ],
    )

with a2_col:
    agent_card(
        "Agent 2 — Style & Security",
        "Security, code smells, style",
        [
            f"{style_counts['critical']} critical",
            f"{style_counts['warning']} warnings",
            f"{style_counts['info']} notes",
        ],
    )

st.markdown("<div style='height:24px'></div>", unsafe_allow_html=True)


tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Bug / Logic", "Style / Security", "Code Diff"])

with tab1:
    ov_l, ov_r = st.columns([1.3, 1], gap="large")
    with ov_l:
        section_header("Executive Summary", "Generated by the orchestrator.", icon_name="summary")
        summary_card = st.container(border=True)
        with summary_card:
            
            st.markdown(final_report)

    with ov_r:
        section_header("Score Breakdown", "How the 82/100-style score was calculated.", icon_name="score")
        score_breakdown(bug_counts, style_counts, score)

        st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)

        section_header("Findings by Severity", "Combined across both agents.", icon_name="chart")
        severity_bar_chart(bug_counts, style_counts)

with tab2:
    section_header("Bug & Logic Agent Findings", icon_name="bug")
    render_feedback(bug_feedback, empty_message="No bugs or logic issues found.")

with tab3:
    section_header("Style & Security Agent Findings", icon_name="shield")
    render_feedback(style_feedback, empty_message="No style or security issues found.")

with tab4:
    section_header("Reviewed Diff", icon_name="code")
    st.code(diff_shown, language="diff")